name: wrf-py-env

channels:
  - conda-forge
  - defaults

dependencies:
  - netCDF4
  - matplotlib
  - cmasher
  - cartopy
#  - pynio     #Reccomended by wrf-python, not needed for Plotting a Two-dimensional Field script
#  - pyngl     #Reccomended by wrf-python, not needed for Plotting a Two-dimensional Field script
#  - basemap   #Reccomended by wrf-python, not needed for Plotting a Two-dimensional Field script
  - wrf-python
  - imageio
  - imageio-ffmpeg
  - metpy
  - setuptools
