name: wrf-py-env

channels:
  - conda-forge
  - defaults

dependencies:
  - netCDF4==1.6
  - matplotlib==3.5.2
  - cartopy==0.20.3
#  - pynio==1.5     #Reccomended by wrf-python, not needed for Plotting a Two-dimensional Field script
#  - pyngl==1.6     #Reccomended by wrf-python, not needed for Plotting a Two-dimensional Field script
#  - basemap==1.3   #Reccomended by wrf-python, not needed for Plotting a Two-dimensional Field script
  - wrf-python==1.3.4
  - imageio==2.19.3
  - imageio-ffmpeg==0.4.7