import os
import sys

# Adds folder to python path search
sys.path.insert(1, "/".join(__file__.split("/")[:-2]))

import argparse
from rip_toolkit.utils import str2bool
import rip_toolkit as ript


def cli():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--task",
        type=str,
        default="point_trajectory",
        choices=ript.__all__,
    )
    parser.add_argument(
        "--image_path",
        type=str,
        default=os.environ.get("RIP_IMAGE_PATH", None),
        help="Path to the apptainer image. Can also be set via the environment variable `RIP_IMAGE_PATH`.",
    )
    parser.add_argument(
        "--wrfout_dir",
        type=str,
        default=None,
        help="Path to the directory containing the wrfout files.",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default=None,
        help="Path to the directory where output files will be saved.",
    )
    parser.add_argument(
        "--tag",
        type=str,
        default=None,
        help="A tag to identify the run/file/trajectory/plot.",
    )
    parser.add_argument(
        "--time_from",
        type=float,
        default=None,
        help="Start model time for preprocessing, in hours since simulation start (inclusive).",
    )
    parser.add_argument(
        "--time_to",
        type=float,
        default=None,
        help="End model time for preprocessing, in hours since simulation start (inclusive).",
    )
    parser.add_argument(
        "--time_step",
        type=float,
        default=None,
        help="Requested RIPDP output interval in hours for ptimes. RIPDP can only emit times that exist in the provided WRF history data.",
    )
    parser.add_argument(
        "--batch_size",
        type=int,
        default=50,
        help="The number of wrfout files to process in each batch (progress is saved at the end of each batch).",
    )
    parser.add_argument(
        "--ripdp_data",
        type=str,
        default=None,
        help="Full path to the RIPDP prefix file (e.g. RIPDP/rdp_test) generated by the preprocess function.",
    )
    parser.add_argument(
        "--traj_t_0",
        type=float,
        default=None,
        help="Particle release time (model time) in hours since simulation start.",
    )
    parser.add_argument(
        "--traj_t_f",
        type=float,
        default=None,
        help="Time until which the trajectory will be computed (model time) in hours since simulation start.",
    )
    parser.add_argument(
        "--traj_x",
        type=int,
        default=None,
        help="Grid x position from which the particle is released.",
    )
    parser.add_argument(
        "--traj_y",
        type=int,
        default=None,
        help="Grid y position from which the particle is released.",
    )
    parser.add_argument(
        "--traj_z", type=float, default=None, help="Pressure level (hPa)."
    )
    parser.add_argument(
        "--swarm_x",
        type=str,
        default=None,
        help="List of grid x positions from which the particles are released, separated by commas.",
    )
    parser.add_argument(
        "--swarm_y",
        type=str,
        default=None,
        help="List of grid y positions from which the particles are released, separated by commas.",
    )
    parser.add_argument(
        "--swarm_z",
        type=str,
        default=None,
        help="List of pressure levels (hPa) from which the particles are released, separated by commas.",
    )
    parser.add_argument(
        "--traj_diagnostic_group",
        type=str,
        default=None,
        help="Diagnostics to be computed along trajectory. Call `diagnostic_groups(group_name)` to see them.",
        choices=["base", "short", "long"],
    )
    parser.add_argument(
        "--traj_tags",
        type=str,
        default=None,
        help="A list of trajectory tags to be used in the plot, separated by commas.",
    )
    parser.add_argument(
        "--traj_cols",
        type=str,
        default=None,
        help="A list of colors to be used in the plot, separated by commas.",
    )
    parser.add_argument(
        "--traj_dt",
        type=int,
        default=None,
        help="Trajectory numerical timestep (seconds).",
    )
    parser.add_argument(
        "--file_dt",
        type=int,
        default=None,
        help="Time interval in RIPDP data (seconds).",
    )
    parser.add_argument(
        "--hydrometeor",
        type=int,
        default=0,
        help="Set to 0 for Air Parcel trajectories, or 1 for Hydrometeor trajectories.",
    )
    parser.add_argument(
        "--format",
        type=str,
        default="pdf",
        help="Format of the output plot.",
    )
    parser.add_argument(
        "--run_script",
        type=str,
        default=None,
        help="Path to the script to be executed inside the container.",
    )
    parser.add_argument(
        "--raise_on_error",
        type=str2bool,
        default=1,
        help="If True, raises a RuntimeError if the container exits with a non-zero exit code. If False, returns the exit code.",
    )
    parser.add_argument(
        "--load_apptainer_module",
        type=str2bool,
        default=1,
        help="If True, loads the apptainer module before running the container. Can also be set via the environment variable `LOAD_APPTAINER_MODULE=1`.",
    )
    parser.add_argument(
        "--module_init_cmd",
        type=str,
        default="source /etc/profile.d/modules.sh",
        help="Command to initialize the module system (default: 'source /etc/profile.d/modules.sh').",
    )
    parser.add_argument(
        "--module_load_cmd",
        type=str,
        default="module load apptainer",
        help="Command to load the apptainer module (default: 'module load apptainer').",
    )

    args = parser.parse_args()

    if args.traj_diagnostic_group is not None:
        args.traj_diagnostics = ript.diagnostic_groups(args.traj_diagnostic_group)

    traj_tags = args.traj_tags.split(",") if args.traj_tags is not None else []
    traj_cols = (
        args.traj_cols.split(",") if args.traj_cols is not None else ript.colors()
    )
    if args.traj_tags is not None:
        traj_tags_cols = {
            tag: traj_cols[i % len(traj_cols)] for i, tag in enumerate(traj_tags)
        }

    match args.task:
        case "preprocess":
            rdp = ript.preprocess(
                wrfout_dir=args.wrfout_dir,
                output_dir=args.output_dir,
                file_tag=args.tag,
                time_from=args.time_from,
                time_to=args.time_to,
                time_step=args.time_step,
                image_path=args.image_path,
                batch_size=args.batch_size,
            )
            print(f"ripdp_data={rdp}")
        case "point_trajectory":
            pt = ript.point_trajectory(
                wrfout_dir=args.wrfout_dir,
                output_dir=args.output_dir,
                ripdp_data=args.ripdp_data,
                traj_tag=args.tag,
                traj_t_0=args.traj_t_0,
                traj_t_f=args.traj_t_f,
                traj_x=args.traj_x,
                traj_y=args.traj_y,
                traj_z=args.traj_z,
                traj_dt=args.traj_dt,
                file_dt=args.file_dt,
                hydrometeor=args.hydrometeor,
                traj_diagnostics=args.traj_diagnostics,
                image_path=args.image_path,
            )
            print(f"point_traj={pt}")
        case "swarm_trajectories":
            st = ript.swarm_trajectories(
                wrfout_dir=args.wrfout_dir,
                output_dir=args.output_dir,
                ripdp_data=args.ripdp_data,
                traj_tag=args.tag,
                traj_t_0=args.traj_t_0,
                traj_t_f=args.traj_t_f,
                traj_x=args.swarm_x.split(","),
                traj_y=args.swarm_y.split(","),
                traj_z=args.swarm_z.split(","),
                traj_dt=args.traj_dt,
                file_dt=args.file_dt,
                hydrometeor=args.hydrometeor,
                traj_diagnostics=args.traj_diagnostics,
                colors=traj_cols,
                image_path=args.image_path,
            )
            print(f"traj_tags={','.join(st.keys())}")
            print(f"traj_cols={','.join(st.values())}")
        case "plot_trajectories":
            ript.plot_trajectories(
                output_dir=args.output_dir,
                ripdp_data=args.ripdp_data,
                traj_tags_colors=traj_tags_cols,
                plot_tag=args.tag,
                format=args.format,
                image_path=args.image_path,
            )
        case "run_rip_container":
            ript.run_rip_container(
                wrfout_dir=args.wrfout_dir,
                output_dir=args.output_dir,
                ripdp_dir=args.ripdp_dir,
                file_tag=args.tag,
                image_path=args.image_path,
                run_script=args.run_script,
                raise_on_error=args.raise_on_error,
                load_apptainer_module=args.load_apptainer_module,
                module_init_cmd=args.module_init_cmd,
                module_load_cmd=args.module_load_cmd,
            )
        case "get_model_times":
            mt = ript.get_model_times(wrfout_dir=args.wrfout_dir)
            print(mt)
        case "date_model_times":
            mt = ript.get_model_times(wrfout_dir=args.wrfout_dir)
            dmt = ript.date_model_times(mt)
            print(dmt)
        case "print_model_times":
            mt = ript.get_model_times(wrfout_dir=args.wrfout_dir)
            ript.print_model_times(mt)
        case "diagnostic_groups":
            for group in ["base", "short", "long"]:
                dg = ript.diagnostic_groups(group)
                print(f"Group: {group}")
                print(dg)
        case "colors":
            print(ript.colors())
        case _:
            print(f"Unknown task: {args.task}")
            sys.exit(1)


if __name__ == "__main__":
    cli()
