#!/bin/bash

# Checks that there are enough inputs
if [ $# -lt 1 ]; then
    echo "Not enough arguments provided. I need at least the folder name to clean."
    echo "Usage: ./clean.sh [Directory] [keep_RIPDP?]"
    echo "For example: "
    echo "./clean.sh Sample 0"
    echo "will delete all non-input files from the folder \"Sample\", including the ripdp preprocessing"
    echo "On the other hand, if the command is"
    echo "./clean.sh Sample 1"
    echo "all non-input files from the folder \"Sample\" will be deleted, but the ripdp preprocessing will be kept"
    echo ""
    exit 1
fi

# Gets inputs
folder=$1				# Saves input 1 (folder to clean)
keeprdp=${2:-0}         # Saves input 2 (option to keep rip dp preprocessing files). Default is 0.
keepplots=${3:-0}       # Saves input 3 (option to keep plots generated by rip). Default is 0.

# Checks folder exists
if [ ! -d "$folder" ]; then
    echo "Cannot find $folder."
    exit 1
else
    if [[ $folder = */ ]]; then
    # Deletes trailing /
        folder=${folder::-1}
    fi
fi

if [ $keeprdp -eq 0 ]; then
    #Remove preprocessing files
    rm -f ./$folder/RIPDP/rdp_*_*.*_*
    rm -f ./$folder/RIPDP/rdp_*.minfo
    rm -f ./$folder/RIPDP/rdp_*.xtimes
fi

#Remove log files and intermediate rip processing files
rm -f ./$folder/*/*.out
rm -f ./$folder/*/*.diag
rm -f ./$folder/*/*.traj
rm -f ./$folder/*.out

if [ $keepplots -eq 0 ]; then
    #Remove plot files
    rm -f ./$folder/*.cgm
    rm -f ./$folder/*/*.cgm
    rm -f ./$folder/*.pdf
    rm -f ./$folder/*/*.pdf
    rm -f ./$folder/*.ps
    rm -f ./$folder/*/*.ps
fi